### ISSUE TITLE
Loading Spinner Needed

### ISSUE THREAD

**Issue by akashkolakkal** [akashkolakkal/csi#15]
**Describe the bug**
When first loading the website, a lot of components take time to load. Need a loading spinner for it. 

**To Reproduce**
1. Visit https://csiace.com

**Expected behavior**
A loading spinner before every component loads.

**Screenshots**
NA

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: All devices
 - OS: All OS'
 - Browser: All browsers
 - Version: NA

**Additional context**
NA

**Comment by joshs-code** [comment]
Sent a PR.  Added loading spinner to your pages.

**Comment by akashkolakkal** [comment]
#16 Checkout added response

**Comment by vaibhavraut07** [comment]
Hey Akash PR Raised for spinner issue as well as added skeleton page. skeleton page is being used currently in code you can just remove commented code for spinner to view spinner effect.
